services:
  api:
    container_name: contactkeeper-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      AuthTriggerUrl: http://functions:80/api/authtrigger
    depends_on:
      - functions

  functions:
    container_name: functions
    build:
      context: ../Functions
      dockerfile: ./Dockerfile
    ports:
      - "7124:80"
    environment:
      AzureWebJobsStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      WEBSITES_INCLUDE_CLOUD_CERTS: "true"
    depends_on:
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:5432"