apiVersion: v1
kind: ConfigMap
metadata:
  name: contactkeeper-config
  namespace: contactkeeper
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  AuthTriggerUrl: "http://contactkeeper-functions/api/authtrigger"