apiVersion: v1
kind: Secret
metadata:
  name: contactkeeper-secrets
  namespace: contactkeeper
type: Opaque
stringData:
  DatabaseSettings__Production: "Server=sqlserver,1433;Database=Contactkeeper;User Id=sa;Password=GosthTro0per.ZUZ236;Trusted_Connection=False;TrustServerCertificate=True;"
  AzureWebJobsStorage:  "DefaultEndpointsProtocol=https;AccountName=stcontactkeeperfunc;AccountKey=v18yzividriQj97A6eUDb7tYRpklNgZZ9QtMs2w1loWvu6rRiGwVv1R7vv7gqi3VreV9bfPnH9zM+ASt3+TDNg==;EndpointSuffix=core.windows.net"