name: ci-cd pipeline

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
           
            - name: Setup dotnet 8.0
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '8.0'      
           
            - name: Clean build artifacts
              run: dotnet clean ContactKeeper.csproj
            
            - name: Install dependencies
              run: dotnet restore ContactKeeper.csproj
      
            - name: Build project 
              run: dotnet build ContactKeeper.csproj -c Release
              
            - name: Run tests
              run: dotnet test ./ContactKeeper.Test/ContactKeeper.Test.csproj --no-build --verbosity normal --configuration Release
                 
            - name: Run tests with diagnostics
              env:
                DOTNET_CLI_TELEMETRY_OPTOUT: 1
                DOTNET_NOLOGO: true
              run: dotnet test ./ContactKeeper.Test/ContactKeeper.Test.csproj --diag:testlog.txt --logger "console;verbosity=detailed"
      
            - name: Upload test logs
              uses: actions/upload-artifact@v4
              with:
                name: testlog.txt
                path: testlog.txt
              
