name: ci-cd pipeline

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest                    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          install: true

      - name: docker login
        uses: docker/login-action@v2
        with:             
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/main-contactkeeper-api:latest
          push: true  
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Run tests
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_NOLOGO: true
          ASPNETCORE_ENVIRONMENT: ${{ secrets.ENV_DEVOPS }}                
        run: dotnet test ./ContactKeeper.Test/ContactKeeper.Test.csproj --configuration Release --verbosity normal

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name contactkeeper ${{ secrets.DOCKER_USERNAME }}/main-contactkeeper-api:latest
