name: ci-cd pipeline

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: List files
              run: ls -R

            - name: Setup dotnet 8.0
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '8.0'          
             
            - name: Install dependencies
              run: dotnet restore ./ContactKeeper/ContactKeeper.csproj
              

            - name: Run tests
              run: dotnet test ./ContactKeeper.Test/ContactKeeper.csproj
            
            - name: Build project
              run: dotnet build ./ContactKeeper/ContactKeeper.csproj
