name: ci-cd pipeline test for endpoint tests
trigger:
- main

pool:
  name: 'AZ-Pool'

steps:
- task: UseDotNet@2
  displayName: 'Setup .NET Core'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration Release --no-restore
  displayName: 'Build'

- script: dotnet test --no-build --verbosity normal
  displayName: 'Run tests'
